backend:
  name: git-gateway
  branch: main  # Change to your GitHub branch if not main

media_folder: assets/uploads  # Folder for uploaded images

collections:
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "about" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: blog
    label: Blog
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }